// todo-list-svelte/src/lib/TodoForm.svelte
<script>
  import { todos } from "../store";

  let newTodo = "";

  function addNewTodo() {
    if (!newTodo.trim().length) return;

    todos.update((todos) => {
      return [...todos, { id: todos.length, title: newTodo, completed: false }];
    });

    newTodo = "";
  }
</script>

<form on:submit|preventDefault={addNewTodo} class="mb-3">
  <label for="newTodo" class="form-label">New Todo</label>
  <input
    type="text"
    class="form-control"
    id="newTodo"
    placeholder="Make a Todo List"
    bind:value={newTodo}
  />
  <button type="submit" class="btn btn-primary mt-2">Add Todo</button>
</form>

// todo-list-react/src/components/TodoForm.jsx
import React, { useState, useContext } from 'react'

import { TodoContext } from '../contexts/TodoContext'

const TodoForm = () => {
  const [todos, setTodos] = useContext(TodoContext);

  const [newTodo, setNewTodo] = useState('');

  const handleChange = (e) => {
    setNewTodo(e.target.value);
  }

  const addNewTodo = (e) => {
    if (!newTodo.trim().length) return;

    e.preventDefault();

    setTodos([...todos, { id: todos.length, title: newTodo, completed: false }]);
    setNewTodo('');
  }

  return (
    <form onSubmit={addNewTodo} className="mb-3">
      <label htmlFor="newTodo" className="form-label">New Todo</label>
      <input type="text" className="form-control" id="newTodo" placeholder="Make a Todo List" onChange={handleChange} value={newTodo}/>
      <button type="submit" class="btn btn-primary mt-2">Add Todo</button>
    </form>
  )
}

export default TodoForm
