// todo-list-react/src/App.jsx
import React from 'react'

import TodoForm from './components/TodoForm'
import TodoList from './components/TodoList'

import { TodoProvider } from './contexts/TodoContext';

const App = () => {
  return (
    <TodoProvider>
      <div class="container py-4">
        <TodoForm/>
        <TodoList/>
      </div>
    </TodoProvider>
  )
}

export default App

// todo-list-vue/src/App.vue
<template>
  <div class="container py-4">
    <TodoForm />
    <TodoList />
  </div>
</template>

<script>
import { defineComponent } from "vue";

import TodoForm from "./components/TodoForm.vue";
import TodoList from "./components/TodoList.vue";

export default defineComponent({
  name: "App",

  components: {
    TodoForm,
    TodoList,
  },
});
</script>
