// todo-list-react/src/components/TodoListItem.jsx
import React from 'react'

const TodoListItem = ({ todo, onDeleteTodo, onCompleteTodo }) => {

  const deleteTodo = () => {
    onDeleteTodo(todo.id)
  }

  const completeTodo = () => {
    onCompleteTodo(todo.id)
  }

  return (
    <li className="list-group-item d-flex align-items-center">
      <label className="flex-fill">
        <input type="checkbox" className="form-check-input me-1" checked={todo.completed} onChange={completeTodo} />
        {todo.title}
      </label>
      <button className="btn btn-danger" onClick={deleteTodo}>Delete</button>
    </li>
  )
}

export default TodoListItem

// todo-list-vue/src/components/TodoListItem.vue
<template>
  <li class="list-group-item d-flex align-items-center">
    <label class="flex-fill">
      <input
        :checked="todo.completed"
        @input="completeTodo"
        class="form-check-input me-1"
        type="checkbox"
      />
      {{ todo.title }}
    </label>
    <button class="btn btn-danger" @click="deleteTodo">Delete</button>
  </li>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "TodoListItem",

  props: {
    todo: Object,
  },

  setup(props, { emit }) {
    function deleteTodo() {
      emit("deleteTodo", props.todo.id);
    }

    function completeTodo() {
      emit("completeTodo", props.todo.id);
    }

    return {
      deleteTodo,
      completeTodo,
    };
  },
});
</script>
