// todo-list-svelte/src/lib/TodoListItem.svelte
<script>
  export let todo;

  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  function deleteTodo() {
    dispatch("deleteTodo", todo.id);
  }

  function completeTodo() {
    dispatch("completeTodo", todo.id);
  }
</script>

<li class="list-group-item d-flex align-items-center">
  <label class="flex-fill">
    <input
      checked={todo.completed}
      on:change={completeTodo}
      class="form-check-input me-1"
      type="checkbox"
    />
    {todo.title}
  </label>
  <button class="btn btn-danger" on:click={deleteTodo}>Delete</button>
</li>

// todo-list-vue/src/components/TodoListItem.vue
<template>
  <li class="list-group-item d-flex align-items-center">
    <label class="flex-fill">
      <input
        :checked="todo.completed"
        @change="completeTodo"
        class="form-check-input me-1"
        type="checkbox"
      />
      {{ todo.title }}
    </label>
    <button class="btn btn-danger" @click="deleteTodo">Delete</button>
  </li>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "TodoListItem",

  props: {
    todo: Object,
  },

  setup(props, { emit }) {
    function deleteTodo() {
      emit("deleteTodo", props.todo.id);
    }

    function completeTodo() {
      emit("completeTodo", props.todo.id);
    }

    return {
      deleteTodo,
      completeTodo,
    };
  },
});
</script>
